# Generated by Django 2.2.14 on 2021-04-22 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channelid', models.TextField(unique=True)),
                ('author', models.TextField(null=True, unique=True)),
                ('title', models.TextField(db_index=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('hidden', models.BooleanField(db_index=True, default=False)),
                ('thumbnail', models.TextField(default='')),
                ('uploads_playlist', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ListaReproduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('idvideo', models.CharField(max_length=500, verbose_name='Id del Video')),
                ('fecha_subida', models.DateField(blank=True, null=True, verbose_name='Fecha Ejecución')),
                ('hora_subida', models.TimeField(blank=True, null=True, verbose_name='Hora Ejecución')),
                ('visto', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtubeid', models.TextField(unique=True)),
                ('title', models.TextField(db_index=True, default='')),
                ('duration', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0, null=True)),
                ('favorite_count', models.IntegerField(default=0, null=True)),
                ('uploaded', models.DateTimeField(db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField()),
                ('description', models.TextField(default='')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='youtube.Category')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='youtube.Channel')),
            ],
            options={
                'ordering': ['-uploaded'],
            },
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['uploader', 'deleted', '-uploaded'], name='youtube_vid_uploade_bb5325_idx'),
        ),
    ]
