# Generated by Django 3.0.4 on 2021-04-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaReproduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('idvideo', models.CharField(max_length=500, verbose_name='Id del Video')),
                ('fecha_subida', models.DateField(blank=True, null=True, verbose_name='Fecha Ejecución')),
                ('hora_subida', models.TimeField(blank=True, null=True, verbose_name='Hora Ejecución')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
