# Generated by Django 2.2.14 on 2021-04-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listareproduccion',
            name='link_promo',
            field=models.URLField(blank=True, null=True, verbose_name='Promoción Url'),
        ),
    ]
