# Generated by Django 3.0.4 on 2021-04-12 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_listareproduccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listareproduccion',
            name='status',
        ),
    ]
